version: "3"

services:
  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    ports:
      - "5601:5601"
    networks:
      - kibana-network
networks:
  kibana-network:
    external:
      name: external-opencast-net
